### ISSUE TITLE
dbdoclet Java Runtime Requirements

### ISSUE THREAD

**Issue by stolp** [mfuchs23/dbdoclet#5]
When using dbdoclet 8.02 I noticed that it requires a Java 8 runtime environment since it has been compiled with  -target 1.8 settings.

Since we are forced to build our project using a Java 7 runtime due to other dependencies (enunciate) we are no longer able to use this version and have to step back to version 7.x.

Is the 1.8 target really required by the sources or would it be possible to distribute a version compiled with an earlier target version?

**Comment by mfuchs23** [comment]
I like using lambda expressions, so the source code is really 1.8 :-( Isn't it possible to create the javadoc in a single step, using a different JDK?

**Comment by stolp** [comment]
Thanks for the hint, but this is a multi-module maven build making a hard to add hacks like this. We are trying to migrate to enunciate 2.0.0 now, which brings Java 8 support for the rescue. So my initial problem seems to be resolving now. While moving to new Java versions surely has its advantages for the author, it may lock out consumers from updating, which I wanted to bring up with this issue. Thanks for creating dbdoclet and your explanation.
